# Generated by Django 4.2.27 on 2026-01-23 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_reply_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='thread',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.category'),
        ),
    ]
